version: 0.2
env:
  variables:
    S3_BUCKET: portfolio-codebuild
    APP_NAME: "portfolio"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "pre build"
      - npm i     
  build:
    commands:
      - echo "building"
      - npm run build
  post_build:
    commands:
    # Clear S3 bucket.
    - aws s3 rm s3://${S3_BUCKET} --recursive
    - echo S3 bucket is cleared.
    # Copy dist folder to S3 bucket, As of Angular 6, builds are stored inside an app folder in distribution and not at the root of the dist folder
    - aws s3 cp dist/ s3://${S3_BUCKET}/${APP_NAME} --recursive
    - aws s3 cp appspec.yml s3://${S3_BUCKET}/${APP_NAME} --recursive # Add appspec to deploy
     - aws s3 cp scripts/ s3://${S3_BUCKET}/${APP_NAME} --recursive # Add appspec to deploy

    - echo Build completed on `date`
artifacts:
  #base-directory: dist/ #  base-directory: dist/my-angular-project
  files:
    - 'appspec.yml'
    - 'scripts/*'
    - 'dist/*'
    - 'dist/**/*'
cache:
  paths:
    - '/root/.npm/**/*'
    - '/node_modules/'

